# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define the job to test the Android project
jobs:
  test-android:
    # Specify the execution environment using a CircleCI Docker image for Android.
    docker:
      - image: circleci/android:api-30

    # Add steps to execute within the job
    steps:
      # Checkout the code from the repository
      - checkout

      # Download Android dependencies
      - run:
          name: Install Dependencies
          command: sdkmanager --install "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      # Restore dependencies cache
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "build.gradle" }}
            - gradle-cache-v1-

      # Run Gradle commands to build and test the project
      - run:
          name: Build Project
          command: ./gradlew assembleDebug

      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      - run:
          name: Run Instrumentation Tests
          command: ./gradlew connectedAndroidTest

      # Save dependencies cache
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      # Store test results for CircleCI Test Summary
      - store_test_results:
          path: build/test-results

      # Store build artifacts (e.g., APK files or logs)
      - store_artifacts:
          path: build/outputs/apk

# Define the workflow to orchestrate the job
workflows:
  test-android-workflow:
    jobs:
      - test-android